// Number of films per game
export const FILMS_PER_GAME = 5;

export const GENRE_MATCHING_CONFIG = {
  MAX_SCORE: 80,
} as const;

export const ANIMATION_TIMING = {
  REVEAL_DELAY_MS: 300,
  REVEAL_STEP_CORRECT_MS: 1000,
  REVEAL_STEP_MISSED_MS: 600,
  INCORRECT_HOLD_MS: 1000,
  FLY_ANIMATION_MS: 800,
  LAYOUT_DELAY_MS: 350,
} as const;
