name: Terragrunt Apply

on:
  workflow_call:
    inputs:
      working_directory:
        required: true
        type: string
      output_key:
        required: false
        type: string

      env_vars:
        description: 'Environment variables to set (KEY=VALUE format, one per line)'
        required: false
        type: string
        default: ''
    outputs:
      terragrunt_output:
        description: 'The value of the requested output key'
        value: ${{ jobs.apply.outputs.terragrunt_output }}

env:
  AWS_REGION: eu-west-1
  TERRAFORM_VERSION: 1.5.7
  TERRAGRUNT_VERSION: 0.54.12

jobs:
  apply:
    name: Apply
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    outputs:
      terragrunt_output: ${{ steps.output.outputs.value }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-deploy-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: false

      - name: Setup Terragrunt
        run: |
          wget -q https://github.com/gruntwork-io/terragrunt/releases/download/v${{ env.TERRAGRUNT_VERSION }}/terragrunt_linux_amd64
          wget -q https://github.com/gruntwork-io/terragrunt/releases/download/v${{ env.TERRAGRUNT_VERSION }}/SHA256SUMS
          grep terragrunt_linux_amd64 SHA256SUMS > terragrunt_SHA256SUM
          sha256sum -c terragrunt_SHA256SUM
          chmod +x terragrunt_linux_amd64
          sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt

      - name: Set Environment Variables
        if: ${{ inputs.env_vars != '' }}
        run: |
          echo "${{ inputs.env_vars }}" >> $GITHUB_ENV

      - name: Terragrunt Apply
        working-directory: ${{ inputs.working_directory }}
        env:
          API_READ_ACCESS_TOKEN: ${{ secrets.API_READ_ACCESS_TOKEN }}
          SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
          ADMIN_IPS: ${{ secrets.ADMIN_IPS }}
        run: |
          terragrunt apply -auto-approve

      - name: Get Output
        id: output
        if: ${{ inputs.output_key != '' }}
        working-directory: ${{ inputs.working_directory }}
        run: |
          VALUE=$(terragrunt output -raw ${{ inputs.output_key }})
          echo "value=$VALUE" >> $GITHUB_OUTPUT
